### ISSUE TITLE
Why Slavery is not reading from the slave db.

### ISSUE THREAD

**Issue by larryzhao** [kenn/slavery#17]
I am setting up slavery, and pointing `development_slave` to an empty database. Then I fire up `rails c` and run `Slavery.on_slave { User.find(3) }`. What I expect is, it ends up with `ActiveRecord::NotFound` but it find the correct record (it has to be from my master db). And I could see this log coming from development.log: `[slave]  User Load (36.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1`, indicating it goes to the Slave.

And I could be sure `Slavery.disabled` is `nil`.

Here's my `database.yml`:

```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  pool: 16
  username: root
  password: admin
  host: localhost
  strict: false

development: &development
  <<: *default
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("MYSQL_PORT", 3306) %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "admin") %>
  database: <%= ENV.fetch("MYSQL_DATABASE", "maleskine") %>
  strict: false

development_slave:
  <<: *default
  host: 127.0.0.1
  port: 3306
  username: root
  password: admin
  database: maleskine_test
  strict: false
```

Is there anything that I've done wrong?
