### ISSUE TITLE
already initialized constant SlaverySlaveConnectionHolder

### ISSUE THREAD

**Issue by caseyprovost** [kenn/slavery#27]
After setting up a very basic slave in development I tried running a simple `Slavery.on_slave{ User.count }` and I get a recursive `slavery-3.0.0/lib/slavery/connection_holder.rb:22: warning: already initialized constant SlaverySlaveConnectionHolder` error

I am on rails 4.2.10 with ruby 2.3.3p222

**Comment by kenn** [comment]
cc @asanghi any insights? I haven't gotten around to upgrading yet.

**Comment by caseyprovost** [comment]
It might also be be good to have documentation around using raw SQL if it doesn't work like this:

```ruby
result = Slavery.on_slave{ ActiveRecord::Base.connection.execute('SELECT * FROM users') }
```

**Comment by asanghi** [comment]
We have this in production and see no problems. I can investigate though. @caseyprovost can you post your database.yml? Your original example is pretty standard and should work.

**Comment by kenn** [comment]
The only case I can think of is that you are running a slave query from multiple threads at the same time, creating a race condition initializing `Slavery.slave_connections`.

Do you have something related? (e.g. `config/initializers`, `before|after_fork` in `config/puma.rb`, etc.)

**Comment by caseyprovost** [comment]
We use Unicorn and a failure standard configuration I think, which I shared below. I am sure it is just a MonkeyPatch I am missing or something.

```yaml
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: chewy_development

development_slave:
  <<: *default
  database: chewy_development_secondary
```

What is the downside of doing something like this instead?

```ruby
class ReportObject < ApplicationRecord
  self.table_name = 'some_table'
  establish_connection(:development_slave)
end

ReportObject.connection.exec('SELECT COUNT(*) FROM some_table')
```

or 

```ruby
def on_slave(&block)
  databases = YAML.load(File.read('config/database.yml'))
  connection = ActiveRecord::Base.establish_connection(databases["#{Rails.env}_slave"])
  result = yield
  connection.disconnect!
  result
end
```
